export const user_action_types = {
  SET_USER: "SET_USER",
  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
};

export const all_user_action_types = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
};

export const components_action_types = {
  TOGGLE_INFOSIDEBAR: "TOGGLE_INFOSIDEBAR",
  TOGGLE_PROFILE_SIDEBAR: "TOGGLE_PROFILE_SIDEBAR",
};
